---
image: williamyeh/ansible:ubuntu16.04

before_script:
  - apt-get update -qq
  - apt-get install -y git python-apt
  - pip install -r requirements.txt
  - ansible-galaxy install -r tests/requirements.yml

validate:
  script:
    - molecule lint
    - cd tests
    - ansible-playbook test.yml -i inventory --check

test_azure_edge:
  script:
    - ansible-playbook tests/test.yml -i tests/inventory -vv
