# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
# These tasks deploy an IoT Edge module.

- name: show edge to install
  debug:
    msg: "Deploying IoT Edge '{{ azure_edge_name }}'."

- name: incorporate collected facts from roles run at driver
  set_fact:
    azure_groups: "{{ hostvars['localhost']['azure_groups'] }}"
  when:
    - azure_groups is not defined
    - hostvars is defined
    - hostvars['localhost'] is defined
    - hostvars['localhost']['azure_groups'] is defined

- name: Include OS-specific tasks
  include_tasks: "{{ os_tasks }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: true
  loop_control:
    loop_var: os_tasks

- name: show edge details
  block:
    - debug:
        msg: "Configuring connection for IoT Edge '{{ azure_edge_name }}'."
    - debug:
        msg: "Connecting to hub '{{ azure_iot_hub_name }}'."
    - debug:
        msg: "Known edge facts: '{{ azure_groups }}'."
  when: azure_groups is defined

- name: set the connection string from previously discovered values
  set_fact:
    connection_string_primary: "HostName=\
      {{ azure_iot_hub_name }}.azure-devices.net;\
      DeviceId={{ azure_edge_name }};\
      SharedAccessKey={{ azure_groups[azure_edge_name].primaryKey }}"
  when:
    - azure_groups is defined

- name: Inject configuration parameters.
  replace:
    dest: /etc/iotedge/config.yaml
    regexp: '<ADD DEVICE CONNECTION STRING HERE>'
    replace: "{{ connection_string_primary }}"
  when:
    - connection_string_primary is defined

- name: Restart service iotedge
  service:
    name: iotedge
    state: restarted
  when:
    - ansible_distribution == 'Ubuntu'
