# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
# These tasks deploy an IoT Edge module.

- name: show edge to install
  debug:
    msg: "Deploying IoT Edge '{{ azure_edge_name }}'."

- name: import the APT repo key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: add Microsoft repository
  apt_repository:
    repo: deb https://packages.microsoft.com/ubuntu/16.04/prod xenial main
    state: present
    filename: microsoft-prod
    update_cache: true
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '16.04'

- name: install the container runtime, cli, and iotedge
  apt:
    name: "{{ item }}"
  with_items:
    - moby-engine
    - moby-cli

- name: install iotedge
  apt:
    name: "{{ item }}"
  with_items:
    - iotedge

- name: set the connection string from previously discovered values
  set_fact:
    connection_string_primary: "HostName=\
      {{ azure_iot_hub_name }}.azure-devices.net;\
      DeviceId={{ azure_edge_name }};\
      SharedAccessKey={{ azure_groups[azure_edge_name].primaryKey }}"
  when:
    - azure_groups is defined

- name: Inject configuration parameters.
  replace:
    dest: /etc/iotedge/config.yaml
    regexp: '<ADD DEVICE CONNECTION STRING HERE>'
    replace: "{{ connection_string_primary }}"
  when:
    - connection_string_primary is defined

- name: Restart service iotedge
  service:
    name: iotedge
    state: restarted
